### ISSUE TITLE
API Gateway 구현

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#10]
## Description
API Gateway 서버 구현하기

## Todo
- [x] infra 폴더 아래에 eureka, gateway 생성
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항

**Comment by vo0a** [comment]
리팩토링 기간에 'SonarQube를 통한 코드 분석 및 품질 향상' 진행하겠습니다.
