### ISSUE TITLE
채팅 서버 FCM 알림 보내기 버그 fix

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#101]
## Description
채팅 서버 FCM 알림 보내는 메소드에서 발생하는 버그 해결하기

## Todo
- [x] restTemplate 관련 버그 fix
- [x] fcm server 의 request 참고하여 알맞은 request 보내기
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
