### ISSUE TITLE
README.md 수정

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#107]
## Description 
코드 리뷰 가이드 수정 사항 반영

## Todo
- [x] fcm 서버 포트번호 8089 -> 8087 로 변경
- [x] fcm 서버 FCM 아이콘 추가
- [x] chat-api 서버 이름 chatroom 으로 변경
   - 포트번호, 아키텍처 그림

## ETC
기타사항
