### ISSUE TITLE
파일 서버 테스트

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#11]
## Description
설명을 작성하세요.

## Todo
- [ ] 파일 생성 API 테스트
- [ ] 파일 조회 API 테스트
- [ ] 파일 삭제 API 테스트
- [ ] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상
