### ISSUE TITLE
폴더 구조 재구성

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#121]
## Description 
 GitLab 제출을 위하여 폴더 구조 재구성

## Todo
- [ ] chatting-service 폴더 내에 chat, presence, fcm 넣기
- [ ] membership-service 폴더 내에 auth, membership, file, chatroom 넣기
- [ ] infrastructure 폴더 내에 eureka, gateway
