### ISSUE TITLE
피드 API 구현

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#29]
## Description
유저 프로필 피드에 관련된 기능을 구현한다.

## Todo
- [x] API 명세서 작성
- [x] 피드 사진 삭제 API 구현
- [x] 사진 공개 여부 설정 API 구현
- [x] 유저 전체 피드 불러오기 API 구현
- [x] 유저 전체 프로필 사진 불러오기 API 구현
- [x] 유저 전체 프로필 배경사진 불러오기 API 구현
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
Pagination 추후 고려
