### ISSUE TITLE
멤버십 서버 구축

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#3]
## Description
유저의 프로필에 대해 CRUD 기능을 구현한다.

## Todo
- [x] 내 프로필(사진, 배경사진, 상태 메시지) 등록하기
- [x] 유저 프로필(사진, 배경사진, 상태 메시지) 가져오기 
- [x] 내 프로필(사진, 배경사진, 상태 메시지) 편집 
- [x] SonarQube 코드 품질 검사
- [x] Google CheckStyle 적용 확인

## ETC
인증서버가 완료되면 인가 로직이 추가적으로 구현되어야한다.
