### ISSUE TITLE
오픈 프로필 API 구현

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#30]
## Description
채팅방 내 오픈 프로필에 관련된 기능을 개발한다.

## Todo
- [x] API 명세서 작성
- [x] 오픈 프로필 생성 API 구현
- [x] 오픈 프로필 조회 API 구현
- [x] 오픈 프로필 수정 API 구현
- [x] 오픈 프로필 삭제 API 구현
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상
