### ISSUE TITLE
채팅방 API 서버 구현

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#35]
## Description
채팅과 관련된 REST API를 구현한다.

## Todo
- [x] API 명세서 작성
- [x] 채팅방 생성 API
- [x] 채팅방 초대 API
- [x] 채팅방 상세 조회 API
- [x] 채팅방 리스트 조회 API
- [x] 채팅방 닫기 API
- [x] 채팅방 나가기 API
- [x] 채팅방 수정 API
- [x] 채팅방 내에서 업로드 된 모든 파일 조회 API 
- [x] Google Checksytle 검사

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
멀티 프로필, 오픈 채팅방은 추후에 보완 예정으로 구현하겠습니다.
