### ISSUE TITLE
멤버십 서버 테스트

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#4]
## Description
Membership 서버의 모든 API를 테스트한다.

## Todo
- [ ] **`POST`** `/api/profile/me` API 테스트
- [ ] **`PATCH`** `/api/profile/me` API 테스트
- [ ] **`GET`** `/api/profile/{id}` API 테스트

## ETC
인가, 파일 서버 필요
