### ISSUE TITLE
회원가입시 기본 프로필 자동생성하기

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#43]
## Description
auth 서버에서 회원가입시 membership 서버 '프로필 생성' API 를 호출한다. userId 는 token 이 아니라 requestBody 에 들어간다.

## Todo
- [x] userId, isDefault 만 넣어서 API 호출
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
