### ISSUE TITLE
친구 API 개발

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#45]
## Description
친구 서버 API

## Todo
- [x] API 명세서 작성
- [x] (회원가입 후 첫 로그인 시) 자동 친구 추가 API 
  > 1. 클라이언트에서 서버로 연락처 리스트를 보냄
  > 2. 서버에서 '가입된 친구들'의 default 프로필을 보내줌 (친구추가 된 것으로 간주)

- [x] (수동 친구 추가) 사용자의 unique한 정보(이메일 또는 폰번호)를 입력하여 가입된 친구 검색 -> 친구 추가
- [x] 친구 리스트 조회 Get
- [x] 친구 관계 설정 Put

## ETC
친구 리스트에 필요한 데이터
profileId, imageUrl(프로필이미지), description, nickname
