### ISSUE TITLE
인증서버 폴더링 변경

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#50]
## Description
user, token, device 폴더를 domain 의 하위 폴더로 구성하기

## Todo
- [x] domain 폴더 생성
- [x] user, token, device 폴더 이동
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항

**Comment by vo0a** [comment]
완료했습니다.
