### ISSUE TITLE
프레젠스 서버 구현

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#54]
## Description
특정 사용자가 특정 채팅방에 접속중임을 기록한다.
특정 사용자가 특정 채팅방에 접속했을 때 입장을 기록하고, 채팅방 나가기(뒤로가기)가 되었을 때 기록을 삭제한다.

## Todo
- [ ] TCP vs WebSocket
- [ ] DB 선택
- [ ] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
