### ISSUE TITLE
API Gateway에서 access token 만료 응답 수정 요청

### ISSUE THREAD

**Issue by paksuua** [DevCamp2Flame/FlameTalk_Server#56]
## Description
현재: API Gateway에서 access token 만료 시 plain text로 `Invalid Token`이 뜸
요청: access token 만료 시 Body를 보내줘야 함 (Error, Success Body는 상관 없음. 클라에게 공유만 해주면 됨)
~~단, 이때 보내주는 HTTP Status code는 다른 API response status로 보내준 적 없는 unique한 code여야 함~~

## Todo
- [x] accessToken 만료시 Httpstatus 200, body status 302 주기
  - 안드로이드에서는 이 응답을 받으면 토큰 재발급 요청을 바로 실행
- [x] refreshToken 만료하여 토큰 재발급이 실패했을 경우 에러코드 307 반환.
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상
