### ISSUE TITLE
채팅서버 Message response 에 message type 추가

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#60]
## Description
request에는 message type이 있으나, response 에는 message type 이 없어 client 작업에 어려움을 겪음. 추가 요망

## Todo
- [x] Message class 에 타입 추가
- [ ] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
