### ISSUE TITLE
채팅서버 메시지 history API 구현

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#62]
## Description
채팅방에서 마지막으로 읽은 위치를 넘겨주면, 그 이후의 메시지를 return 한다.

## Todo
- [x] /history API 만들기
- [ ] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
