### ISSUE TITLE
파일 서버 구축

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#7]
## Description
설명을 작성하세요.

## Todo
- [x] S3 연동
- [x] 파일 생성 API
- [x] 파일 조회 API
- [x] 파일 삭제 API
- [x] 디렉토리 설정
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상
