### ISSUE TITLE
README.md 수정

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#74]
## Description
2차 코드 리뷰 피드백 반영하여 보완하기

## Todo
- [x] 가독성 고려하여 최대한 한글로 작성
- [x] 목차 작성
- [x] Database 여러개 사용하는 이유 작성
- [x] 아키텍처 수정본 첨부
- [x] 접어두기 지양하기. 최대한 정보를 펼쳐둠

## ETC
프로젝트 설명.txt 같은 파일도 필요하다.
