### ISSUE TITLE
프로필 업데이트 시 친구에게 보여줄 프로필 Preview 업데이트

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#79]
## Description
현재는 유저가 프로필을 업데이트해도 친구에게 업데이트 된 프로필이 보여지지 않습니다

## Todo
- [x] 프로필 업데이트 로직에 친구에게 보여주는 프로필 프리뷰 업데이트하는 로직 추가
- [x] Google Checksytle 검사

## ETC
기타사항

**Comment by SuyeonChoi** [comment]
## TODO 추가
- [ ] 프로필 수정시 기본 프로필이 존재하는지 검증
