### ISSUE TITLE
인증 서버 보완사항 적용

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#9]
## Todo
- [x] 토큰 관리 DB MySQL 에서 redis 로 변경
- [x] 이메일 중복 API 생성
   - 회원가입 중간에 확인할 이메일 중복 확인 API 만들어야 함
- [x] 사용자 redis key 변경
- [x] Jwt 관련 Exception 처리
- [x] 회원탈퇴시 redis에 저장된 기존 토큰과 비교
- [x] ErrorCode 의 status 와 실제 response HttpStatus 를 일치시킴
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항

**Comment by vo0a** [comment]
리팩토링기간에 'SonarQube를 통한 코드 분석 및 품질 향상' 진행하겠습니다.
