### ISSUE TITLE
채팅 서비스 API Gateway 적용

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#90]
## Description
 chat, presence 서버 eureka 설정 후, API Gateway yml 파일 수정하여 API Gateway 거쳐 통신할 수 있도록 한다.

## Todo
- [x] chat, presence 서버 eureka client 설정 (8085, 8086)
- [x] gateway 서버 yml 수정
- [x] 통신 테스트
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
