### ISSUE TITLE
채팅 서버 schema.cql 추가

### ISSUE THREAD

**Issue by vo0a** [DevCamp2Flame/FlameTalk_Server#93]
## Description
채팅서버 keysapce 부터 data 까지 저장하는 명령문 저장

## Todo
- [x] chat 서버에 schema.cql 추가
- [x] Google Checksytle 검사
- [ ] SonarQube를 통한 코드 분석 및 품질 향상

## ETC
기타사항
