### ISSUE TITLE
채팅방 대화상대 초대 API request 추가

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#97]
## Description
현재는 채팅방이 생성되거나 초대될때 lastReadMessage가 null로 초기화된다. 이 경우 클라이언트에서 채팅방의 메세지를 모두 가져오므로 유저가 초대된 시점의 메세지를 request에 추가한다.

## Todo
- [x] API 문서 업데이트
- [x] 채팅방 대화상대 초대 API request에 lastReadMessage 추가
- [x] Google Checksytle 검사
