### ISSUE TITLE
채팅방 내 파일 리스트 조회 API 서버 변경

### ISSUE THREAD

**Issue by SuyeonChoi** [DevCamp2Flame/FlameTalk_Server#98]
## Description
파일 서버로 위임한다.

## Todo
- [x] API 문서 업데이트
- [x] 채팅방 내 파일 리스트 조회 API를 파일 서버에서 처리하도록 변경
- [x] Google Checksytle 검사
